name: Build and Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Add Polyfill for structuredClone
        run: |
          echo "if (typeof structuredClone === 'undefined') { globalThis.structuredClone = (obj) => { return JSON.parse(JSON.stringify(obj)); }; }" > polyfill.js
        shell: cmd

      - name: Build the project
        run: npm run build

      - name: Lint the project
        run: npx eslint . --fix
